FROM elixir:1.9.0-alpine as build

# install build dependencies
RUN apk add --update git build-base python

# prepare build dir
RUN mkdir /app
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
RUN mix deps.get

# build project
COPY lib lib
COPY priv priv

CMD [ "mix", "phx.server" ]
