version: '3.4'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
