version: '3.4'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - db
