apiVersion: v1
kind: Service
metadata:
  name: salsa-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 4000
  selector:
    app: salsa-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: salsa-web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: salsa-web
    spec:
      containers:
        - name: salsa-web
          image: salsacr.azurecr.io/salsa-release:latest
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: database_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: secret_key_base
